version: '3'

services:
  mou-api:
    build: .
    ports:
      - 80:8000
    volumes:
      - ./:/user/src/app
    env_file:
      - ./.env/.production
    networks:
      - mou-api-network

networks:
  mou-api-network:
